export type ImagePlacement = {
  id: "front" | "back";
  label: string;
  fileName: string;
  src: string;
  pdfData: string;
  aspectRatio: number;
  x: number;
  y: number;
  width: number;
  scale: number;
  rotation: number;
  tilt: number;
  cropTop: number;
  cropRight: number;
  cropBottom: number;
  cropLeft: number;
  flipHorizontal: boolean;
  flipVertical: boolean;
};
